const sliderImg = [
    {
    key: 1,
    image: '/Assets/Images/bmw_x4.jpg',
    name: 'BMW',
    alt: 'img1',
  },
  {
    key: 2,
    image: '/Assets/Images/ford_fiesta.jpg',
    name: 'BMW',
    alt: 'img2',
  },
  {
    key: 3,
    image: '/Assets/Images/jaguar_xk.jpg',
    name: 'BMW',
    alt: 'img3',
  },
  {
    key: 4,
    image: '/Assets/Images/land_rover_discovery.jpg',
    name: 'BMW',
    alt: 'img4',
  },
  {
    key: 6,
    image: '/Assets/Images/renault_clio.jpg',
    name: 'BMW',
    alt: 'img5',
  },
  {
    key: 7,
    image: '/Assets/Images/1D80H2L509599_16884_ff2d07075a92a66220803687e71dae6f_669_033e1b3018f499fcfad3dcaa1c71d080.webp',
    name: 'BMW',
    alt: 'img1',
  },
  {
    key: 8,
    image: '/Assets/Images/ford_fiesta.jpg',
    name: 'BMW',
    alt: 'img2',
  },
  {
    key: 9,
    image: '/Assets/Images/jaguar_xk.jpg',
    name: 'BMW',
    alt: 'img3',
  },
  {
    key: 10,
    image: '/Assets/Images/land_rover_discovery.jpg',
    name: 'BMW',
    alt: 'img4',
  },
  {
    key: 11,
    image: '/Assets/Images/renault_clio.jpg',
    name: 'BMW',
    alt: 'img5',
  }
  ]
  
  
//   // const FilterCar = [
//   //   {
//   //   key: 1,
//   //   image: '/Assets/Images/_CJWghhfJsWYs47ERRJHfV3BR58.jpg',
//   //   name: 'BMW1',
//   //   redirection: '#',
//   //   dealerName: 'ebay',
//   //   dealerlogo:'/Assets/Images/dealer/ebay.png',
//   //   Currency: '$',
//   //   price : '139,000',
//   //   millege: '29,200 mi',
//   //   location: 'Los Angeles, CA',
//   //   postDate: '12 days ago',
//   //   shortDesc: 'I bought this car August 2020 from Livermore Porsche. At the time, it had about 2200 miles',
//   //   alt: 'img1',
//   //   zippostal:"234",
//   //   distance:'200',
//   //   model:"2017",
//   //   cartype:"used"
//   // },
//   // {
//   //   key: 2,
//   //   image: '/Assets/Images/_Q3ZUScuhgJb5dAbgckKXMXEUDI.jpg',
//   //   name: 'BMW2',
//   //   redirection: '#',
//   //   dealerName: 'autosgilles',
//   //   dealerlogo:'/Assets/Images/dealer/dealer2.jpeg',
//   //   Currency: '$',
//   //   price : '139,000',
//   //   millege: '29,200 mi',
//   //   location: 'Los Angeles, CA',
//   //   postDate: '12 days ago',
//   //   shortDesc: 'I bought this car August 2020 from Livermore Porsche. At the time, it had about 2200 miles',
//   //   alt: 'img2',
//   //   zippostal:"231",
//   //   distance:'300',
//   //   model:"2018",
//   //   cartype:"new"
//   // },
//   // {
//   //   key: 3,
//   //   image: '/Assets/Images/_Sbymlbl41mQCbwr3R3Z1S_siqo.jpg',
//   //   name: 'BMW3',
//   //   redirection: '#',
//   //   dealerName: 'autoshop',
//   //   dealerlogo:'/Assets/Images/dealer/dealer/dealer3.jpg',
//   //   Currency: '$',
//   //   price : '139,000',
//   //   millege: '29,200 mi',
//   //   location: 'Los Angeles, CA',
//   //   postDate: '12 days ago',
//   //   shortDesc: 'I bought this car August 2020 from Livermore Porsche. At the time, it had about 2200 miles',
//   //   alt: 'img3',
//   //   zippostal:"235",
//   //   distance:'400',
//   //   model:"2020",
//   //   cartype:"new"
//   // },
//   // {
//   //   key: 4,
//   //   image: '/Assets/Images/7NHVYIAKI5XBPZVXTIZM5BLHIY-cr-540.jpg',
//   //   name: 'BMW4',
//   //   redirection: '#',
//   //   dealerName: 'benitez',
//   //   dealerlogo:'/Assets/Images/dealer/dealer4.jpeg',
//   //   Currency: '$',
//   //   price : '139,000',
//   //   millege: '29,200 mi',
//   //   location: 'Los Angeles, CA',
//   //   postDate: '12 days ago',
//   //   shortDesc: 'I bought this car August 2020 from Livermore Porsche. At the time, it had about 2200 miles',
//   //   alt: 'img4',
//   //   zippostal:"234",
//   //   distance:'200',
//   //   model:"2017",
//   //   cartype:"used"
//   // },
//   // {
//   //   key: 6,
//   //   image: '/Assets/Images/1-1.jpg',
//   //   name: 'BMW5',
//   //   redirection: '#',
//   //   dealerName: 'autodeaership',
//   //   dealerlogo:'/Assets/Images/dealer/dealer5.png',
//   //   Currency: '$',
//   //   price : '139,000',
//   //   millege: '29,200 mi',
//   //   location: 'Los Angeles, CA',
//   //   postDate: '12 days ago',
//   //   shortDesc: 'I bought this car August 2020 from Livermore Porsche. At the time, it had about 2200 miles',
//   //   alt: 'img5',
//   //   zippostal:"231",
//   //   distance:'300',
//   //   model:"2018",
//   //   cartype:"new"
//   // },
//   // {
//   //   key: 7,
//   //   image: '/Assets/Images/1.jpg',
//   //   name: 'BMW6',
//   //   redirection: '#',
//   //   dealerName: 'lorem',
//   //   dealerlogo:'/Assets/Images/dealer/lorem.png',
//   //   Currency: '$',
//   //   price : '139,000',
//   //   millege: '29,200 mi',
//   //   location: 'Los Angeles, CA',
//   //   postDate: '12 days ago',
//   //   shortDesc: 'I bought this car August 2020 from Livermore Porsche. At the time, it had about 2200 miles',
//   //   alt: 'img1',
//   //   zippostal:"235",
//   //   distance:'300',
//   //   model:"2019",
//   //   cartype:"used"
//   // },
//   // {
//   //   key: 8,
//   //   image: '/Assets/Images/6DbWDFPlLNXlnZaHvcIaoOgzjS4.jpg',
//   //   name: 'BMW7',
//   //   redirection: '#',
//   //   dealerName: 'lorem',
//   //   dealerlogo:'/Assets/Images/dealer/lorem.png',
//   //   Currency: '$',
//   //   price : '139,000',
//   //   millege: '29,200 mi',
//   //   location: 'Los Angeles, CA',
//   //   postDate: '12 days ago',
//   //   shortDesc: 'I bought this car August 2020 from Livermore Porsche. At the time, it had about 2200 miles',
//   //   alt: 'img2',
//   //   zippostal:"235",
//   //   distance:'400',
//   //   model:"2019",
//   //   cartype:"new"
//   // },
//   // {
//   //   key: 9,
//   //   image: '/Assets/Images/2JYKP6KJCLDHIKC3E2XLHI2S34-cr-1400.jpg',
//   //   name: 'BMW8',
//   //   redirection: '#',
//   //   dealerName: 'benitez',
//   //   dealerlogo:'/Assets/Images/dealer/dealer4.jpeg',
//   //   Currency: '$',
//   //   price : '139,000',
//   //   millege: '29,200 mi',
//   //   location: 'Los Angeles, CA',
//   //   postDate: '12 days ago',
//   //   shortDesc: 'I bought this car August 2020 from Livermore Porsche. At the time, it had about 2200 miles',
//   //   alt: 'img3',
//   //   zippostal:"236",
//   //   distance:'500',
//   //   model:"2019",
//   //   cartype:"new"
//   // },
//   // {
//   //   key: 10,
//   //   image: '/Assets/Images/Y263005_3f96c496558f24155e0142d4c64e7512_5_25b2f935bd7ecd3367467e53abce9abf.webp',
//   //   name: 'BMW9',
//   //   redirection: '#',
//   //   dealerName: 'ebay',
//   //   dealerlogo:'/Assets/Images/dealer/ebay.png',
//   //   Currency: '$',
//   //   price : '139,000',
//   //   millege: '29,200 mi',
//   //   location: 'Los Angeles, CA',
//   //   postDate: '12 days ago',
//   //   shortDesc: 'I bought this car August 2020 from Livermore Porsche. At the time, it had about 2200 miles',
//   //   alt: 'img4',
//   //   zippostal:"236",
//   //   distance:'400',
//   //   model:"2020",
//   //   cartype:"used"
//   // },
//   // // {
//   // //   key: 11,
//   // //   image: '/Assets/Images/ZQLKY4R2ERCOWQONKHXNJJMCM4-cr-540.jpg',
//   // //   name: 'BMW10',
//   // //   redirection: '#',
//   // //   dealerName: 'carHub',
//   // //   Currency: '$',
//   // //   price : '139,000',
//   // //   millege: '29,200 mi',
//   // //   location: 'Los Angeles, CA',
//   // //   postDate: '12 days ago',
//   // //   shortDesc: 'I bought this car August 2020 from Livermore Porsche. At the time, it had about 2200 miles',
//   // //   alt: 'img5',
//   // // }
//   // ]
  


  export default sliderImg;
//   // export { FilterCar };
